name: 'Compile APSIMX'
description: 'Checks out and compiles APSIM Next Generation'
inputs:
  repo-url:
    description: 'Git URL of APSIMX source'
    required: false
    default: 'APSIMInitiative/ApsimX'
  branch:
    description: 'Branch to checkout'
    required: false
    default: 'master'
runs:
  using: "composite"
  steps:
    - name: Checkout APSIMX source
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repo-url }}
        ref: ${{ inputs.branch }}

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    
    - name: Debug files
      run: ls -al
      shell: bash

    - name: Build APSIMX
      run: dotnet build Models/Models.csproj -c Release
      shell: bash

    - name: Add Models to PATH
      run: echo "$(pwd)/Bin/Release/net8.0" >> $GITHUB_PATH
      shell: bash
