name: Test APSIMX Compile Action

on:
  push:
    branches: [main]

jobs:
  test-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Run local APSIMX compile action
        uses: byzheng/apsimx-actions/.github/actions/compile-apsimx
