name: Test APSIMX Compile Action

on:
  push:
    branches: [main]

jobs:
  test-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Compile APSIMX
        uses: byzheng/apsimx-actions@main
        with:
          run-test-example: 'true'